commerce_option.commerce_product_option.*:
  type: config_entity
  label: 'Product attribute'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    elementType:
      type: string
      label: 'Element type'
    productTypes:
      type: sequence
      label: 'Product types'
      sequence:
        type: mapping
        label: 'Product type'
        mapping:
          target_id:
            type: string
            label: 'Value'
