commerce_option.commerce_product_option.*:
  type: config_entity
  label: 'Product option'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    elementType:
      type: string
      label: 'Element type'
